import { Dimensions, StyleSheet } from "react-native";

import { color } from "../components/utilitise/colors";
import { moderateScale } from "../services/theme";

export const commonStyles = StyleSheet.create({
  body: {
    marginTop: "6%",
    backgroundColor: "#edeef5",
    minHeight: Dimensions.get("window").height,
    position: "relative",
  },
  iconWrapper: {
    height: 30,
    width: 30,
    borderRadius: 100,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  closeIconWrapper: {
    position: "absolute",
    right: 5,
    top: 8,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#eee",
    height: 30,
    width: 30,
    borderRadius: 100,
  },
  closeIcon: {
    color: "#57534e",
  },
  input: {
    height: 40,
    width: "100%",
    borderColor: color.gray,
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 9,
    zIndex: 0,
  },
  formContainer: {
    backgroundColor: "#fff",
    paddingVertical: 20,
    paddingHorizontal: "3.5%",
    margin: 10,
    borderRadius: 7,
  },
  formHeader: {
    fontSize: 18,
    textAlign: "center",
    marginBottom: 10,
  },
  selectView: {
    position: "absolute",
    left: 0,
    backgroundColor: "#fff",
    width: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    borderRadius: 5,
    zIndex: 100,
  },
  heading: {
    fontSize: moderateScale(18),
    marginTop: 15,
    color: "#4b5cbf",
    borderBottomColor: "#4b5cbf",
    borderBottomWidth: 1,
    width: "50%",
    textAlign: "center",
    borderBottomRightRadius: 7,
    borderBottomLeftRadius: 7,
    backgroundColor: "#edeef5",
    shadowColor: "#4b5cbf",
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.4,
    shadowRadius: 3,
    elevation: 5,
    alignSelf: "center",
    paddingBottom: 3,
  },
  tableRow: {
    flexDirection: "row",
    justifyContent: "center",
    borderColor: color.gray,
    borderWidth: 1,
    width: "100%",
    paddingHorizontal: 6,
    paddingVertical: 4,
  },

  sip: {
    borderRadius: 15,
    borderWidth: 0.6,
    borderColor: color.gray,
    paddingVertical: 5,
    paddingHorizontal: 10,
    alignSelf: "flex-start",
    flexDirection: "row",
    columnGap: 10,
    alignItems: "center",
  },
  sipContainer: {
    flexDirection: "row",
    columnGap: 10,
    flexWrap: "wrap",
  },
});
