import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    position: "absolute",
    bottom: 0,
    left: 0,
    backgroundColor: "#fff",
    width: "100%",
    paddingTop: 10,
    paddingHorizontal: 15,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopRightRadius: 17,
    borderTopLeftRadius: 17,
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: -6,
    },
    shadowOpacity: 0.19,
    shadowRadius: 5.62,
    elevation: 6,
    height: 57,
  },
  iconWrapper: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    borderRadius: 5,
    paddingHorizontal: 7,
  },
  plusIcon: {
    color: "#4b5563",
    fontSize: 35,
    marginTop: -15,
    zIndex: 1,
  },
  highlight: {
    backgroundColor: "#2fbd55",
  },
  modal: {
    position: "absolute",
    left: 0,
    backgroundColor: "#fff",
    width: "90%",
    borderRadius: 10,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.19,
    shadowRadius: 5.62,
    elevation: 6,
    paddingBottom: 20,
    zIndex: 60,
  },
  closeIcon: {
    color: "#57534e",
  },
  closeIconWrapper: {
    position: "absolute",
    right: 15,
    top: 8,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#edeef5",
    height: 30,
    width: 30,
    borderRadius: 100,
  },
});
