export const transitions = [
  {
    id: 1,
    fromUserId: 2,
    toUserId: 1,
    fromUserName: "Mohammad Kamal",
    toUserName: "Md Kader",
    amount: 4000,
    date: "05-04-23",
    purpose: "Sales",
  },
  {
    id: 2,
    fromUserId: 2,
    toUserId: 1,
    fromUserName: "Mohammad Kamal",
    toUserName: "Md Kader",
    amount: 1200,
    date: "05-04-23",
    purpose: "Salary",
  },
  {
    id: 4,
    fromUserId: 2,
    toUserId: 1,
    fromUserName: "Mohammad Kamal",
    toUserName: "Md Kader",
    amount: 3000,
    date: "05-04-23",
    purpose: "Sales",
  },
  {
    id: 3,
    fromUserId: 2,
    toUserId: 4,
    fromUserName: "Md Kader",
    toUserName: "Prayas",
    amount: 2500,
    date: "05-04-23",
    purpose: "Purchase",
  },
  {
    id: 5,
    fromUserId: 2,
    toUserId: 1,
    fromUserName: "Mohammad Kamal",
    toUserName: "Md Kader",
    amount: 6000,
    date: "05-04-23",
    purpose: "Sales",
  },
  {
    id: 6,
    fromUserId: 2,
    toUserId: 1,
    fromUserName: "Mohammad Kamal",
    toUserName: "Md Kader",
    amount: 3000,
    date: "05-04-23",
    purpose: "Sales",
  },
  {
    id: 7,
    fromUserId: 2,
    toUserId: 1,
    fromUserName: "Mohammad Kamal",
    toUserName: "Md Kader",
    amount: 5000,
    date: "05-04-23",
    purpose: "Sales",
  },
  {
    id: 8,
    fromUserId: 2,
    toUserId: 1,
    fromUserName: "Mohammad Kamal",
    toUserName: "Md Kader",
    amount: 7000,
    date: "05-04-23",
    purpose: "Sales",
  },
];

export const stockReport = [
  {
    id: 1,
    name: "Original Coffee",
    productId: 12,
    date: "05-04-2023",
    previousStock: 12,
    purchased: 50,
    todaySale: 6,
    remainingStock: 7,
  },
  {
    id: 2,
    name: "Regular Coffee",
    productId: 14,
    date: "05-04-2023",
    previousStock: 15,
    purchased: 0,
    todaySale: 9,
    remainingStock: 13,
  },
];
