export const orderdata = [
  {
    shopInfo: {
      id: 2,
      shopName: "Foysal Store",
      address: "Kandir par, cumilla",
      phone: "01853860483",
      profile: "no-photo.png",
    },
    products: [
      {
        id: 2,
        name: "Regular Coffee",
        price: 465,
        qty: 1,
        total: 465,
      },
    ],
    totalSale: 465,
    billno: "5568",
    status: "Undelivered",
    date: "2023-04-08",
    time: "8:35 pm",
    id: 1,
    due: 0,
    payment: 5600,
    discount: 40,
  },
  {
    shopInfo: {
      id: 2,
      profile: "no-photo.png",
      shopName: "Foysal Store",
      address: "Kandir par, cumilla",
      phone: "01853860483",
    },
    products: [
      {
        id: 2,
        name: "Regular Coffee",
        price: 465,
        qty: 1,
        total: 465,
      },
      {
        id: 1,
        name: "Original Coffee",
        price: 465,
        qty: 1,
        total: 465,
      },
    ],
    totalSale: 465,
    billno: "5568",
    status: "Undelivered",
    date: "2023-04-08",
    time: "8:35 pm",
    id: 2,
    due: 200,
    payment: 5600,
    discount: 40,
    collection: [
      {
        orderId: 2,
        id: 1,
        collectedBy: "Fahim",
        amount: 200,
        date: "12-03-23",
      },
      {
        id: 2,
        orderId: 2,
        collectedBy: "Fahim",
        amount: 100,
        date: "12-03-23",
      },
    ],
  },
];

export const customerData = [
  {
    id: 1,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "no-photo.png",
    phone: "01853860483",
    lastOrder: "02-03-2023",
  },
  {
    id: 2,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "no-photo.png",
    phone: "01853860483",
    lastOrder: "02-03-2023",
  },
  {
    id: 3,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "no-photo.png",
    phone: "01853860483",
    lastOrder: "02-03-2023",
  },
  {
    id: 4,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "no-photo.png",
    phone: "01853860483",
    lastOrder: "02-03-2023",
  },
  {
    id: 5,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "no-photo.png",
    phone: "01853860483",
    lastOrder: "02-03-2023",
  },
  {
    id: 6,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "no-photo.png",
    phone: "01853860483",
    lastOrder: "02-03-2023",
  },
  {
    id: 7,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "no-photo.png",
    phone: "01853860483",
    lastOrder: "02-03-2023",
  },
  {
    id: 8,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "no-photo.png",
    phone: "01853860483",
  },
  {
    id: 9,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "no-photo.png",
    phone: "01853860483",
  },
  {
    id: 10,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "no-photo.png",
    phone: "01853860483",
  },
  {
    id: 11,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "no-photo.png",
    phone: "01853860483",
  },
  {
    id: 12,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "no-photo.png",
    phone: "01853860483",
  },
  {
    id: 13,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "no-photo.png",
    phone: "01853860483",
  },
  {
    id: 14,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "no-photo.png",
    phone: "01853860483",
  },
  {
    id: 15,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "no-photo.png",
    phone: "01853860483",
  },
  {
    id: 16,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "no-photo.png",
    phone: "01853860483",
  },
  {
    id: 17,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "no-photo.png",
    phone: "01853860483",
  },
  {
    id: 18,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "no-photo.png",
    phone: "01853860483",
  },
  {
    id: 19,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "no-photo.png",
    phone: "01853860483",
  },
];

export const products = [
  {
    id: 1,
    name: "Original Coffee",
    stock: 56,
    price: 515,
    totalSold: 47,
    previousDaysSold: 5,
    thisMonthSold: 22,
    profile: "../assets/no-photo.png",
  },
  {
    id: 2,
    name: "Regular Coffee",
    stock: 64,
    price: 465,
    totalSold: 489,
    previousDaySold: 5,
    thisMonthSold: 22,
    profile: "../assets/no-photo.png",
  },
  {
    id: 3,
    name: "Milk Tea",
    stock: 64,
    price: 465,
    totalSold: 489,
    previousDaySold: 5,
    thisMonthSold: 22,
    profile: "../assets/no-photo.png",
  },
];

export const supplyers = [
  {
    id: 1,
    name: "Prayas LTD",
    address: "Dhanmondi",
    phone: "01988784928",
    profile: "../assets/no-photo.png",
    products: [
      { id: 1, name: "Original", purchased: 2000 },
      { id: 2, name: "Regular", purchased: 3400 },
    ],
    totalPurchased: 450000,
    giveAmount: 40000,
    debtAmount: 50000,
  },
  {
    id: 2,
    name: "Switch Cafe",
    address: "Dhaka",
    phone: "01988784928",
    profile: "../assets/no-photo.png",
    products: [
      { id: 3, name: "150ML Cup", purchased: 20000 },
      { id: 4, name: "130ML Cup", purchased: 350000 },
    ],
    totalPurchased: 450000,
    giveAmount: 40000,
    debtAmount: 50000,
  },
];

export const users = [
  {
    id: 1,
    name: "Karim",
    address: "Kandirpar",
    phone: "01988784928",
    designation: "Sales man",
    profile: "",
    delivered: 40,
    average: 4,
  },
  {
    id: 2,
    name: "Habib",
    address: "Kasimpur",
    phone: "01988784928",
    designation: "Manager",
    profile: "",
    delivered: 35,
    average: 3,
  },
];

export const totalReport = [
  {
    id: 1,
    name: "Total Sold",
    amount: 4000000,
    bgColor: "#d5f2db",
    textColor: "#159e31",
  },
  {
    id: 2,
    name: "Due Sold",
    amount: 4000000,
    bgColor: "#f0ebd3",
    textColor: "#9e8715",
  },
  {
    id: 3,
    name: "Due Collection",
    amount: 4000000,
    bgColor: "#d3e9f0",
    textColor: "#2191b0",
  },
  {
    id: 4,
    name: "Purchase",
    amount: 4000000,
    bgColor: "#d5dbf2",
    textColor: "#1933a8",
  },
  {
    id: 5,
    name: "Expense",
    amount: 4000000,
    bgColor: "#edd5ed",
    textColor: "#8f1391",
  },
  {
    id: 6,
    name: "Got Amount",
    amount: 4000000,
    textColor: "#1ba10e",
    bgColor: "#d7edd5",
  },
  {
    id: 7,
    name: "Closing Cash",
    amount: 4000000,
    bgColor: "#c1e0d5",
    textColor: "#178760",
  },
  {
    id: 8,
    name: "Market Due",
    amount: 4000000,
    bgColor: "#ebd1e0",
    textColor: "#87175a",
  },
];

export const accounts = [
  {
    id: 1,
    userId: 2,
    name: "Md Kamal Hossen",
    haveMoney: 3000,
    piority: 1,
    details: [
      {
        id: 1,
        userId: 1,
        name: "Habib Ulla",
        amount: 4000,
        date: "05-04-23",
        status: "Debt",
      },
      {
        id: 2,
        userId: 1,
        name: "Habib Ulla",
        amount: 1000,
        date: "05-04-23",
        status: "Pay Debt",
      },
    ],
  },
  {
    id: 2,
    userId: 2,
    name: "Mohammad Karim",
    haveMoney: 8000,
    piority: 2,
    details: [
      {
        id: 1,
        userId: 1,
        name: "Habib Ulla",
        amount: 300,
        date: "05-04-23",
        status: "Debt",
      },
      {
        id: 2,
        userId: 1,
        name: "Habib Ulla",
        amount: 1000,
        date: "05-04-23",
        status: "Debt",
      },
      {
        id: 3,
        userId: 1,
        name: "Karim Khan",
        amount: 1000,
        date: "05-04-23",
        status: "Debt",
      },
      {
        id: 4,
        userId: 1,
        name: "Habib Ulla",
        amount: 300,
        date: "05-04-23",
        status: "Debt",
      },
      {
        id: 5,
        userId: 1,
        name: "Habib Ulla",
        amount: 1000,
        date: "05-04-23",
        status: "Debt",
      },
      {
        id: 6,
        userId: 1,
        name: "Karim Khan",
        amount: 1000,
        date: "05-04-23",
        status: "Debt",
      },
    ],
  },
  {
    id: 3,
    userId: 2,
    name: "Mohammad Karim",
    haveMoney: 30000,
    piority: 1,
    details: [],
  },
];

export const transitions = [
  {
    id: 1,
    fromUserId: 2,
    toUserId: 1,
    fromUserName: "Mohammad Kamal",
    toUserName: "Md Kader",
    amount: 4000,
    date: "05-04-23",
    purpose: "Sales",
  },
  {
    id: 2,
    fromUserId: 2,
    toUserId: 1,
    fromUserName: "Mohammad Kamal",
    toUserName: "Md Kader",
    amount: 1200,
    date: "05-04-23",
    purpose: "Salary",
  },
  {
    id: 4,
    fromUserId: 2,
    toUserId: 1,
    fromUserName: "Mohammad Kamal",
    toUserName: "Md Kader",
    amount: 3000,
    date: "05-04-23",
    purpose: "Sales",
  },
  {
    id: 3,
    fromUserId: 2,
    toUserId: 4,
    fromUserName: "Md Kader",
    toUserName: "Prayas",
    amount: 2500,
    date: "05-04-23",
    purpose: "Purchase",
  },
  {
    id: 5,
    fromUserId: 2,
    toUserId: 1,
    fromUserName: "Mohammad Kamal",
    toUserName: "Md Kader",
    amount: 6000,
    date: "05-04-23",
    purpose: "Sales",
  },
  {
    id: 6,
    fromUserId: 2,
    toUserId: 1,
    fromUserName: "Mohammad Kamal",
    toUserName: "Md Kader",
    amount: 3000,
    date: "05-04-23",
    purpose: "Sales",
  },
  {
    id: 7,
    fromUserId: 2,
    toUserId: 1,
    fromUserName: "Mohammad Kamal",
    toUserName: "Md Kader",
    amount: 5000,
    date: "05-04-23",
    purpose: "Sales",
  },
  {
    id: 8,
    fromUserId: 2,
    toUserId: 1,
    fromUserName: "Mohammad Kamal",
    toUserName: "Md Kader",
    amount: 7000,
    date: "05-04-23",
    purpose: "Sales",
  },
];

export const stockReport = [
  {
    id: 1,
    name: "Original Coffee",
    productId: 1,
    date: "05-04-2023",
    previousStock: 12,
    purchase: 50000,
    todaySale: 7000,
    remainingStock: 7,
  },
  {
    id: 2,
    name: "Regular Coffee",
    productId: 2,
    date: "05-04-2023",
    previousStock: 15,
    purchase: 0,
    todaySale: 2000,
    remainingStock: 13,
  },
  {
    id: 3,
    name: "Milk Tea",
    productId: 3,
    date: "05-04-2023",
    previousStock: 10,
    purchase: 16,
    todaySale: 7,
    remainingStock: 19,
  },
];

export const notes = [
  {
    id: 1,
    heading: "lorem ipsum",
    description: `Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
sunt in culpa qui officia deserunt mollit anim id est laborum.`,
  },
  {
    id: 2,
    heading: "lorem ipsum",
    description: `Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
sunt in culpa qui officia deserunt mollit anim id est laborum.`,
  },
  {
    id: 3,
    heading: "lorem ipsum",
    description: `Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
sunt in culpa qui officia deserunt mollit anim id est laborum.`,
  },
];
