export const orderdata = [
  {
    shopInfo: {
      id: 2,
      shopName: "Foysal Store",
      address: "Kandir par, cumilla",
      phone: "01853860483",
      profile: "../assets/no-photo.png",
    },
    products: [
      {
        id: 2,
        name: "Regular Coffee",
        price: 465,
        qty: 1,
        total: 465,
      },
    ],
    totalSale: 465,
    billno: "5568",
    status: "Undelivered",
    date: "2023-04-08",
    time: "8:35 pm",
    id: 1,
    due: 0,
    payment: 5600,
    discount: 40,
  },
  {
    shopInfo: {
      id: 2,
      profile: "../assets/no-photo.png",
      shopName: "Foysal Store",
      address: "Kandir par, cumilla",
      phone: "01853860483",
    },
    products: [
      {
        id: 2,
        name: "Regular Coffee",
        price: 465,
        qty: 1,
        total: 465,
      },
      {
        id: 1,
        name: "Original Coffee",
        price: 465,
        qty: 1,
        total: 465,
      },
    ],
    totalSale: 465,
    billno: "5568",
    status: "Undelivered",
    date: "2023-04-08",
    time: "8:35 pm",
    id: 2,
    due: 200,
    payment: 5600,
    discount: 40,
    collection: [
      {
        orderId: 2,
        id: 1,
        collectedBy: "Fahim",
        ammount: 200,
        date: "12-03-23",
      },
      {
        id: 2,
        orderId: 2,
        collectedBy: "Fahim",
        ammount: 100,
        date: "12-03-23",
      },
    ],
  },
];

export const customerData = [
  {
    id: 1,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "../assets/no-photo.png",
    phone: "01853860483",
    lastOrder: "02-03-2023",
  },
  {
    id: 2,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "../assets/no-photo.png",
    phone: "01853860483",
    lastOrder: "02-03-2023",
  },
  {
    id: 3,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "../assets/no-photo.png",
    phone: "01853860483",
    lastOrder: "02-03-2023",
  },
  {
    id: 4,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "../assets/no-photo.png",
    phone: "01853860483",
    lastOrder: "02-03-2023",
  },
  {
    id: 5,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "../assets/no-photo.png",
    phone: "01853860483",
    lastOrder: "02-03-2023",
  },
  {
    id: 6,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "../assets/no-photo.png",
    phone: "01853860483",
    lastOrder: "02-03-2023",
  },
  {
    id: 7,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "../assets/no-photo.png",
    phone: "01853860483",
    lastOrder: "02-03-2023",
  },
  {
    id: 8,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "../assets/no-photo.png",
    phone: "01853860483",
  },
  {
    id: 9,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "../assets/no-photo.png",
    phone: "01853860483",
  },
  {
    id: 10,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "../assets/no-photo.png",
    phone: "01853860483",
  },
  {
    id: 11,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "../assets/no-photo.png",
    phone: "01853860483",
  },
  {
    id: 12,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "../assets/no-photo.png",
    phone: "01853860483",
  },
  {
    id: 13,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "../assets/no-photo.png",
    phone: "01853860483",
  },
  {
    id: 14,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "../assets/no-photo.png",
    phone: "01853860483",
  },
  {
    id: 15,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "../assets/no-photo.png",
    phone: "01853860483",
  },
  {
    id: 16,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "../assets/no-photo.png",
    phone: "01853860483",
  },
  {
    id: 17,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "../assets/no-photo.png",
    phone: "01853860483",
  },
  {
    id: 18,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "../assets/no-photo.png",
    phone: "01853860483",
  },
  {
    id: 19,
    owner: "Foysal Ahmed",
    shopName: "Foysal Store",
    address: "Kandir par, cumilla",
    profile: "../assets/no-photo.png",
    phone: "01853860483",
  },
];

export const products = [
  {
    id: 1,
    name: "Original Coffee",
    stock: 56,
    totalSold: 689,
    price: 515,
  },
  {
    id: 2,
    name: "Regular Coffee",
    stock: 64,
    totalSold: 489,
    price: 465,
  },
];
